apiVersion: v1
kind: Secret
metadata:
  name: {{ include "project-name.fullname" . }}-config
  labels:
    {{- include "project-name.labels" . | nindent 4 }}
type: Opaque
data:
{{ if .Values.config }}
  sphinx.conf: {{ .Values.config | b64enc }}
{{ else }}
  sphinx.conf: {{ .Files.Get "files/sphinx.conf" | b64enc }}
{{ end }}